import Foundation

/// The language that should be used in API responses for example for weather condition descriptions
public enum RequestLanguage: String {

    case afrikaans = "af"
    case arabic = "ar"
    case azerbaijani = "az"
    case bulgarian = "bg"
    case catalan = "ca"
    case czech = "cz"
    case danish = "da"
    case german = "de"
    case greek = "el"
    case english = "en"
    case basque = "eu"
    case persian = "fa"
    case finnish = "fi"
    case french = "fr"
    case galician = "gl"
    case hebrew = "he"
    case hindi = "hi"
    case croatian = "hr"
    case hungarian = "hu"
    case indonesian = "id"
    case italian = "it"
    case japanese = "ja"
    case korean = "kr"
    case latvian = "la"
    case lithuanian = "lt"
    case macedonian = "mk"
    case norwegian = "no"
    case dutch = "nl"
    case polish = "pl"
    case portuguese = "pt"
    case portugueseBrasil = "pt_br"
    case romanian = "ro"
    case russian = "ru"
    case swedish = "sv"
    case slovak = "sk"
    case slovenian = "sl"
    case spanish = "es"
    case serbian = "sr"
    case thai = "th"
    case turkish = "tr"
    case ukrainian = "ua"
    case vietnamese = "vi"
    case chineseSimplified = "zh_cn"
    case chineseTraditional = "zh_tw"
    case zulu = "zu"

}
