#!/usr/bin/env bash

if [[ -z $RUNNER_TEMP ]]; then
  echo "RUNNER_TEMP is not set. Setting to root of repository."
  RUNNER_TEMP=$(git rev-parse --show-toplevel)
fi

TARGET=$1
HOSTING_BASE_PATH=$2

if [[ -z $HOSTING_BASE_PATH ]]; then
  HOSTING_BASE_PATH=$TARGET
fi

# First, insert docc-plugin dependency. This is very hacky, but it avoids everyone having to pull in the docc-plugin when they use this library.

sed '/Dependencies declare/a\
.package(url: "https://github.com/apple/swift-docc-plugin", branch: "main"),\
' "Package.swift" > "Package.tmp"

mv "Package.tmp" "Package.swift"

swift package resolve

swift package \
  --allow-writing-to-directory "$RUNNER_TEMP/docs" \
  generate-documentation \
  --target "$TARGET" \
  --transform-for-static-hosting \
  --hosting-base-path "$HOSTING_BASE_PATH" \
  --output-path "$RUNNER_TEMP/docs"

CUSTOM_PATH=$(echo $HOSTING_BASE_PATH | tr '[:upper:]' '[:lower:]')
echo "<script>window.location.href += \"documentation/$CUSTOM_PATH\"</script>" > "$RUNNER_TEMP/docs/index.html"

if [[ -z $GITHUB_ACTIONS ]]; then
  echo "Restoring Package.swift to original state."
  sed -i '' '/swift-docc-plugin/d' "Package.swift"
fi